version: "3.9"

services:
  api:
    image: django-docker:latest
    container_name: django-container
    ports:
      - "8001:8000"
  frontend:
    image: mypost-frontend:latest
    container_name: mypost-frontend-container
    ports:
      - "1488:80"
