version: "3.9"

services:
  api:
    image: mypost-backend-image:latest
    # container_name: mypost-backend-container
    build: ./backend
    ports:
      - "8001:8000"
  frontend:
    image: mypost-frontend-image:latest
    # container_name: mypost-frontend-container
    build: ./frontend
    ports:
      - "1489:80"
