services:
  db:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      PASTGRES_DB: postgres
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  api:
    image: mypost-backend-image:latest
    # container_name: mypost-backend-container
    build: ./backend
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DATABASE_ENGINE: django.db.backends.postgresql
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
 
      DATABASE_PASSWORD: mysecretpassword
      DATABASE_HOST: 63.181.133.208
      DATABASE_PORT: 5432
  frontend:
    image: mypost-frontend-image:latest
    # container_name: mypost-frontend-container
    build:
      context: ./frontend
      # args:
      #   VITE_API_BASE_URL: http://63.181.133.208:8001
    ports:
      - "1489:80"
